package com.chartlite.app.billing

import android.content.Context
import android.content.Intent
import android.graphics.Canvas
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import android.widget.Toast
import androidx.core.content.FileProvider
import java.io.File
import java.io.FileOutputStream

/**
 * Generates a real PDF from a SOAP note and shares it via Android's share sheet.
 * Uses the built-in android.graphics.pdf.PdfDocument — no external dependencies.
 */
object PDFExporter {

    private const val PAGE_WIDTH = 595  // A4 in points (72 dpi)
    private const val PAGE_HEIGHT = 842
    private const val MARGIN = 50f
    private const val LINE_HEIGHT = 14f
    private const val SECTION_GAP = 20f

    fun exportAndShare(context: Context, soapNote: SOAPNoteGenerator.SOAPNote, patientName: String, patientId: String) {
        try {
            val pdf = generatePdf(soapNote, patientName, patientId)
            val file = savePdf(context, pdf, patientId)
            pdf.close()
            sharePdf(context, file)
        } catch (e: Exception) {
            Toast.makeText(context, "PDF export failed: ${e.message}", Toast.LENGTH_SHORT).show()
        }
    }

    private fun generatePdf(
        soapNote: SOAPNoteGenerator.SOAPNote,
        patientName: String,
        patientId: String
    ): PdfDocument {
        val doc = PdfDocument()

        val titlePaint = Paint().apply {
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            textSize = 18f
            color = android.graphics.Color.parseColor("#1B5E20")
        }
        val headerPaint = Paint().apply {
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            textSize = 13f
            color = android.graphics.Color.parseColor("#212121")
        }
        val subheaderPaint = Paint().apply {
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            textSize = 11f
            color = android.graphics.Color.parseColor("#424242")
        }
        val bodyPaint = Paint().apply {
            typeface = Typeface.create(Typeface.MONOSPACE, Typeface.NORMAL)
            textSize = 9.5f
            color = android.graphics.Color.parseColor("#333333")
        }
        val metaPaint = Paint().apply {
            typeface = Typeface.DEFAULT
            textSize = 9f
            color = android.graphics.Color.parseColor("#757575")
        }
        val linePaint = Paint().apply {
            color = android.graphics.Color.parseColor("#E0E0E0")
            strokeWidth = 1f
        }
        val sectionColors = mapOf(
            "SUBJECTIVE" to android.graphics.Color.parseColor("#1565C0"),
            "OBJECTIVE" to android.graphics.Color.parseColor("#2E7D32"),
            "ASSESSMENT" to android.graphics.Color.parseColor("#E65100"),
            "PLAN" to android.graphics.Color.parseColor("#B71C1C")
        )
        val sectionBadgePaint = Paint().apply {
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            textSize = 12f
        }

        var pageNum = 1
        var pageInfo = PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, pageNum).create()
        var page = doc.startPage(pageInfo)
        var canvas = page.canvas
        var y = MARGIN
        val maxWidth = PAGE_WIDTH - 2 * MARGIN

        fun checkPage(needed: Float): Canvas {
            if (y + needed > PAGE_HEIGHT - MARGIN) {
                // Footer on current page
                metaPaint.textAlign = Paint.Align.RIGHT
                canvas.drawText("Page $pageNum", PAGE_WIDTH - MARGIN, PAGE_HEIGHT - 25f, metaPaint)
                metaPaint.textAlign = Paint.Align.LEFT
                doc.finishPage(page)
                pageNum++
                pageInfo = PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, pageNum).create()
                page = doc.startPage(pageInfo)
                canvas = page.canvas
                y = MARGIN
            }
            return canvas
        }

        // ── Header ──
        canvas = checkPage(80f)
        canvas.drawText("CLINICAL NOTE — SOAP FORMAT", MARGIN, y, titlePaint)
        y += 6f
        canvas.drawLine(MARGIN, y, PAGE_WIDTH - MARGIN, y, linePaint)
        y += 16f

        canvas.drawText("Patient: $patientName ($patientId)", MARGIN, y, headerPaint)
        y += LINE_HEIGHT + 2f
        canvas.drawText("Generated by ChartLite v1.0", MARGIN, y, metaPaint)
        y += LINE_HEIGHT
        canvas.drawText("${soapNote.wordCount} words", MARGIN, y, metaPaint)
        y += SECTION_GAP

        // ── SOAP sections ──
        val sections = listOf(
            "SUBJECTIVE" to soapNote.subjective,
            "OBJECTIVE" to soapNote.objective,
            "ASSESSMENT" to soapNote.assessment,
            "PLAN" to soapNote.plan
        )

        for ((sectionTitle, sectionContent) in sections) {
            canvas = checkPage(40f)

            // Section header with colored badge
            val badgeColor = sectionColors[sectionTitle] ?: android.graphics.Color.BLACK
            val badgePaint = Paint().apply {
                color = badgeColor
                alpha = 30
            }
            canvas.drawRoundRect(
                MARGIN, y - 12f,
                MARGIN + subheaderPaint.measureText(sectionTitle) + 16f,
                y + 4f, 4f, 4f, badgePaint
            )
            sectionBadgePaint.color = badgeColor
            canvas.drawText(sectionTitle, MARGIN + 8f, y, sectionBadgePaint)
            y += LINE_HEIGHT + 4f

            // Section body — wrap text
            val lines = sectionContent.split("\n")
            for (line in lines) {
                val wrappedLines = wrapText(line, bodyPaint, maxWidth)
                for (wrapped in wrappedLines) {
                    canvas = checkPage(LINE_HEIGHT)
                    canvas.drawText(wrapped, MARGIN + 4f, y, bodyPaint)
                    y += LINE_HEIGHT
                }
            }
            y += SECTION_GAP / 2

            canvas = checkPage(4f)
            canvas.drawLine(MARGIN, y, PAGE_WIDTH - MARGIN, y, linePaint)
            y += SECTION_GAP / 2
        }

        // ── Footer ──
        canvas = checkPage(40f)
        y += 10f
        canvas.drawText("Electronically generated — ChartLite v1.0", MARGIN, y, metaPaint)
        y += LINE_HEIGHT
        canvas.drawText("This document was auto-generated by ChartLite from a clinical encounter.", MARGIN, y, metaPaint)

        // Page number on last page
        metaPaint.textAlign = Paint.Align.RIGHT
        canvas.drawText("Page $pageNum", PAGE_WIDTH - MARGIN, PAGE_HEIGHT - 25f, metaPaint)
        metaPaint.textAlign = Paint.Align.LEFT

        doc.finishPage(page)
        return doc
    }

    private fun wrapText(text: String, paint: Paint, maxWidth: Float): List<String> {
        if (text.isBlank()) return listOf("")
        val words = text.split(" ")
        val lines = mutableListOf<String>()
        var currentLine = StringBuilder()

        for (word in words) {
            val test = if (currentLine.isEmpty()) word else "$currentLine $word"
            if (paint.measureText(test) <= maxWidth) {
                currentLine = StringBuilder(test)
            } else {
                if (currentLine.isNotEmpty()) lines.add(currentLine.toString())
                currentLine = StringBuilder(word)
            }
        }
        if (currentLine.isNotEmpty()) lines.add(currentLine.toString())
        return lines.ifEmpty { listOf("") }
    }

    private fun savePdf(context: Context, pdf: PdfDocument, patientId: String, prefix: String = "SOAP"): File {
        val dir = File(context.cacheDir, "pdf_exports")
        if (!dir.exists() && !dir.mkdirs()) {
            throw IllegalStateException("Could not create PDF export directory")
        }
        val file = File(dir, "${prefix}_${patientId.take(8)}_${System.currentTimeMillis()}.pdf")
        FileOutputStream(file).use { pdf.writeTo(it) }
        return file
    }

    // ── Summary PDF ──

    fun exportSummaryAndShare(
        context: Context,
        enc: com.chartlite.app.database.entity.EncounterEntity,
        diagnoses: List<com.chartlite.app.model.Diagnosis>,
        medications: List<com.chartlite.app.model.Medication>,
        vitals: com.chartlite.app.model.VitalSigns?,
        allergies: List<String>,
        patientName: String,
        patientId: String
    ) {
        try {
            val pdf = generateSummaryPdf(enc, diagnoses, medications, vitals, allergies, patientName, patientId)
            val file = savePdf(context, pdf, patientId, prefix = "Summary")
            pdf.close()
            sharePdf(context, file, subject = "ChartLite Encounter Summary")
        } catch (e: Exception) {
            Toast.makeText(context, "PDF export failed: ${e.message}", Toast.LENGTH_SHORT).show()
        }
    }

    private fun generateSummaryPdf(
        enc: com.chartlite.app.database.entity.EncounterEntity,
        diagnoses: List<com.chartlite.app.model.Diagnosis>,
        medications: List<com.chartlite.app.model.Medication>,
        vitals: com.chartlite.app.model.VitalSigns?,
        allergies: List<String>,
        patientName: String,
        patientId: String
    ): PdfDocument {
        val doc = PdfDocument()

        val titlePaint = Paint().apply {
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            textSize = 18f
            color = android.graphics.Color.parseColor("#1B5E20")
        }
        val headerPaint = Paint().apply {
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            textSize = 13f
            color = android.graphics.Color.parseColor("#212121")
        }
        val subheaderPaint = Paint().apply {
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            textSize = 11f
            color = android.graphics.Color.parseColor("#424242")
        }
        val bodyPaint = Paint().apply {
            typeface = Typeface.create(Typeface.MONOSPACE, Typeface.NORMAL)
            textSize = 9.5f
            color = android.graphics.Color.parseColor("#333333")
        }
        val metaPaint = Paint().apply {
            typeface = Typeface.DEFAULT
            textSize = 9f
            color = android.graphics.Color.parseColor("#757575")
        }
        val linePaint = Paint().apply {
            color = android.graphics.Color.parseColor("#E0E0E0")
            strokeWidth = 1f
        }

        var pageNum = 1
        var pageInfo = PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, pageNum).create()
        var page = doc.startPage(pageInfo)
        var canvas = page.canvas
        var y = MARGIN
        val maxWidth = PAGE_WIDTH - 2 * MARGIN

        fun checkPage(needed: Float): Canvas {
            if (y + needed > PAGE_HEIGHT - MARGIN) {
                metaPaint.textAlign = Paint.Align.RIGHT
                canvas.drawText("Page $pageNum", PAGE_WIDTH - MARGIN, PAGE_HEIGHT - 25f, metaPaint)
                metaPaint.textAlign = Paint.Align.LEFT
                doc.finishPage(page)
                pageNum++
                pageInfo = PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, pageNum).create()
                page = doc.startPage(pageInfo)
                canvas = page.canvas
                y = MARGIN
            }
            return canvas
        }

        fun drawSection(title: String, items: List<String>) {
            if (items.isEmpty()) return
            canvas = checkPage(40f)
            canvas.drawText(title, MARGIN, y, subheaderPaint)
            y += LINE_HEIGHT + 2f
            for (item in items) {
                val wrapped = wrapText(item, bodyPaint, maxWidth - 8f)
                for (line in wrapped) {
                    canvas = checkPage(LINE_HEIGHT)
                    canvas.drawText(line, MARGIN + 8f, y, bodyPaint)
                    y += LINE_HEIGHT
                }
            }
            y += SECTION_GAP / 2
            canvas = checkPage(4f)
            canvas.drawLine(MARGIN, y, PAGE_WIDTH - MARGIN, y, linePaint)
            y += SECTION_GAP / 2
        }

        // ── Header ──
        canvas = checkPage(80f)
        canvas.drawText("ENCOUNTER SUMMARY", MARGIN, y, titlePaint)
        y += 6f
        canvas.drawLine(MARGIN, y, PAGE_WIDTH - MARGIN, y, linePaint)
        y += 16f
        canvas.drawText("Patient: $patientName ($patientId)", MARGIN, y, headerPaint)
        y += LINE_HEIGHT + 2f
        canvas.drawText("Generated by ChartLite v1.0", MARGIN, y, metaPaint)
        y += SECTION_GAP

        // ── Diagnoses ──
        drawSection("DIAGNOSES", diagnoses.map { dx ->
            val primary = if (dx.isPrimary) " [Primary]" else ""
            "${dx.icd10Code} — ${dx.description}$primary"
        })

        // ── Medications ──
        drawSection("MEDICATIONS", medications.map { med ->
            buildString {
                append(med.name)
                if (med.dose != null) append(" ${med.dose}${med.unit.orEmpty()}")
                if (!med.route.isNullOrBlank()) append(" (${med.route})")
                if (!med.frequency.isNullOrBlank()) append(" — ${med.frequency}")
            }
        })

        // ── Vitals ──
        vitals?.let { v ->
            val items = mutableListOf<String>()
            v.systolicBP?.let { s -> v.diastolicBP?.let { d -> items.add("BP: $s/$d mmHg") } }
            v.pulse?.let { items.add("HR: $it bpm") }
            v.temperature?.let { items.add("Temp: $it °C") }
            v.respiratoryRate?.let { items.add("RR: $it /min") }
            v.oxygenSaturation?.let { items.add("SpO2: $it%") }
            v.weight?.let { items.add("Weight: $it kg") }
            v.height?.let { items.add("Height: $it cm") }
            drawSection("VITAL SIGNS", items)
        }

        // ── Allergies ──
        drawSection("ALLERGIES", allergies)

        // ── Notes ──
        val noteText = enc.freeTextNote.ifBlank { enc.transcript }
        if (noteText.isNotBlank()) {
            // Strip markdown markers for PDF
            val cleaned = noteText.replace(Regex("\\*\\*|^#{1,3}\\s", RegexOption.MULTILINE), "")
            drawSection("CLINICAL NOTES", cleaned.split("\n").filter { it.isNotBlank() })
        }

        // ── Footer ──
        canvas = checkPage(40f)
        y += 10f
        canvas.drawText("Electronically generated — ChartLite v1.0", MARGIN, y, metaPaint)

        metaPaint.textAlign = Paint.Align.RIGHT
        canvas.drawText("Page $pageNum", PAGE_WIDTH - MARGIN, PAGE_HEIGHT - 25f, metaPaint)
        metaPaint.textAlign = Paint.Align.LEFT

        doc.finishPage(page)
        return doc
    }

    private fun sharePdf(context: Context, file: File, subject: String = "ChartLite SOAP Note") {
        val uri = FileProvider.getUriForFile(
            context,
            "${context.packageName}.fileprovider",
            file
        )
        val shareIntent = Intent(Intent.ACTION_SEND).apply {
            type = "application/pdf"
            putExtra(Intent.EXTRA_STREAM, uri)
            putExtra(Intent.EXTRA_SUBJECT, subject)
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
        context.startActivity(Intent.createChooser(shareIntent, "Share PDF"))
    }
}
