package com.chartlite.app.billing

import com.chartlite.app.database.entity.EncounterEntity
import com.chartlite.app.database.entity.LabOrderEntity
import com.chartlite.app.database.entity.ReferralEntity
import com.chartlite.app.database.entity.normalizedReferralOrNull
import com.chartlite.app.model.*
import java.time.Instant
import java.time.ZoneId
import java.time.format.DateTimeFormatter

/**
 * Generates SOAP (Subjective, Objective, Assessment, Plan) notes
 * from structured encounter data.
 *
 * This is real clinical documentation generation — not a placeholder.
 * It constructs each SOAP section from the extracted clinical data
 * following standard medical documentation practices.
 */
object SOAPNoteGenerator {

    data class SOAPNote(
        val subjective: String,
        val objective: String,
        val assessment: String,
        val plan: String,
        val fullText: String,
        val wordCount: Int
    )

    fun generate(
        encounter: EncounterEntity,
        diagnoses: List<Diagnosis>,
        medications: List<Medication>,
        vitals: VitalSigns?,
        allergies: List<String>,
        alerts: List<CDSSAlert>,
        patientName: String = "Patient",
        providerName: String = "Provider",
        labOrders: List<LabOrderEntity> = emptyList(),
        referrals: List<ReferralEntity> = emptyList(),
        examFindings: List<String> = emptyList(),
        investigations: List<Investigation> = emptyList(),
        planItems: List<String> = emptyList(),
        socialHistory: List<String> = emptyList(),
        suggestedDiagnoses: List<Diagnosis> = emptyList()
    ): SOAPNote {
        val dateStr = DateTimeFormatter.ofPattern("dd MMMM yyyy, HH:mm")
            .withZone(ZoneId.systemDefault())
            .format(Instant.ofEpochMilli(encounter.timestamp))

        val subjective = buildSubjective(encounter, allergies, socialHistory)
        val objective = buildObjective(vitals, encounter, labOrders, examFindings, investigations)
        val assessment = buildAssessment(diagnoses, alerts, suggestedDiagnoses)
        val plan = buildPlan(medications, encounter, diagnoses, referrals, planItems)

        val fullText = buildString {
            appendLine("═══════════════════════════════════════")
            appendLine("    CLINICAL NOTE — SOAP FORMAT")
            appendLine("═══════════════════════════════════════")
            appendLine()
            appendLine("Patient: $patientName (${encounter.patientId})")
            appendLine("Date: $dateStr")
            appendLine("Provider: $providerName")
            appendLine("Facility: ${encounter.facilityId}")
            appendLine()
            appendLine("───────────────────────────────────────")
            appendLine("SUBJECTIVE")
            appendLine("───────────────────────────────────────")
            appendLine(subjective)
            appendLine()
            appendLine("───────────────────────────────────────")
            appendLine("OBJECTIVE")
            appendLine("───────────────────────────────────────")
            appendLine(objective)
            appendLine()
            appendLine("───────────────────────────────────────")
            appendLine("ASSESSMENT")
            appendLine("───────────────────────────────────────")
            appendLine(assessment)
            appendLine()
            appendLine("───────────────────────────────────────")
            appendLine("PLAN")
            appendLine("───────────────────────────────────────")
            appendLine(plan)
            appendLine()
            appendLine("───────────────────────────────────────")
            appendLine("Electronically signed by $providerName")
            appendLine("Generated by ChartLite v1.0")
            appendLine("═══════════════════════════════════════")
        }

        val wordCount = fullText.split("\\s+".toRegex()).size

        return SOAPNote(
            subjective = subjective,
            objective = objective,
            assessment = assessment,
            plan = plan,
            fullText = fullText,
            wordCount = wordCount
        )
    }

    private fun buildSubjective(encounter: EncounterEntity, allergies: List<String>, socialHistory: List<String> = emptyList()): String {
        return buildString {
            // Chief complaint from transcript
            val transcript = encounter.freeTextNote.ifBlank { encounter.transcript }
            if (transcript.isNotBlank()) {
                appendLine("Chief Complaint:")
                // Keep the chief complaint to the first clinical sentence. The old
                // minimum index of 100 skipped short first sentences and leaked
                // medications/diagnosis suggestions into this quoted field.
                val clinicalText = transcript
                    .substringBefore("Suggested diagnoses:", transcript)
                    .trim()
                    .removePrefix("Chief concern:")
                    .trim()
                val end = clinicalText.indexOfFirst { it == '.' || it == '!' || it == '?' }
                val cc = (if (end >= 0) clinicalText.take(end + 1) else clinicalText)
                    .take(200)
                appendLine("  \"$cc\"")
                appendLine()
            }

            appendLine("History of Present Illness:")
            if (transcript.isNotBlank()) {
                appendLine("  ${transcript.take(500)}")
            } else {
                appendLine("  Per clinical encounter documentation.")
            }

            if (socialHistory.isNotEmpty()) {
                appendLine()
                appendLine("Social History:")
                socialHistory.forEach { appendLine("  - $it") }
            }

            if (allergies.isNotEmpty()) {
                appendLine()
                appendLine("Allergies: ${allergies.joinToString(", ")}")
            } else {
                appendLine()
                appendLine("Allergies: NKDA (No Known Drug Allergies)")
            }
        }
    }

    private fun buildObjective(vitals: VitalSigns?, encounter: EncounterEntity, labOrders: List<LabOrderEntity> = emptyList(), examFindings: List<String> = emptyList(), investigations: List<Investigation> = emptyList()): String {
        return buildString {
            appendLine("Vital Signs:")
            if (vitals != null) {
                vitals.systolicBP?.let { sys ->
                    val dia = vitals.diastolicBP
                    if (dia != null) {
                        appendLine("  Blood Pressure: $sys/$dia mmHg" + bpCategory(sys, dia))
                    } else {
                        appendLine("  Blood Pressure: $sys/-- mmHg (diastolic not recorded)")
                    }
                }
                vitals.pulse?.let {
                    appendLine("  Heart Rate: $it bpm" + if (it > 100) " (tachycardic)" else if (it < 60) " (bradycardic)" else " (regular)")
                }
                vitals.temperature?.let {
                    appendLine("  Temperature: ${"%.1f".format(it)}°C" + if (it > 38.0) " (febrile)" else " (afebrile)")
                }
                vitals.respiratoryRate?.let {
                    appendLine("  Respiratory Rate: $it breaths/min" + if (it > 20) " (tachypneic)" else "")
                }
                vitals.oxygenSaturation?.let {
                    appendLine("  SpO2: $it%" + if (it < 95) " (hypoxic)" else " (normal)")
                }
                vitals.weight?.let {
                    appendLine("  Weight: ${"%.1f".format(it)} kg")
                }
                vitals.height?.let { h ->
                    appendLine("  Height: ${"%.0f".format(h)} cm")
                    if (h > 0) {
                        vitals.weight?.let { w ->
                            val bmi = w / ((h / 100.0) * (h / 100.0))
                            appendLine("  BMI: ${"%.1f".format(bmi)} kg/m²" + bmiCategory(bmi))
                        }
                    }
                }
            } else {
                appendLine("  Not recorded during this visit.")
            }

            // Lab Results (if any)
            val resultedLabs = labOrders.filter { it.resultValue != null }
            if (resultedLabs.isNotEmpty()) {
                appendLine()
                appendLine("Laboratory Results:")
                resultedLabs.forEach { lab ->
                    val abnormalFlag = if (lab.isAbnormal == true) " [ABNORMAL]" else ""
                    val range = lab.referenceRange?.let { " (ref: $it)" } ?: ""
                    appendLine("  ${lab.testName}: ${lab.resultValue}${lab.resultUnit?.let { " $it" } ?: ""}$range$abnormalFlag")
                }
            }

            val pendingLabs = labOrders.filter { it.resultValue == null && it.status != "CANCELLED" }
            if (pendingLabs.isNotEmpty()) {
                appendLine()
                appendLine("Pending Laboratory Orders:")
                pendingLabs.forEach { lab ->
                    appendLine("  ${lab.testName} (${lab.status}) — ${lab.priority}")
                }
            }

            appendLine()
            appendLine("Physical Examination:")
            if (examFindings.isNotEmpty()) {
                examFindings.forEach { finding ->
                    appendLine("  - $finding")
                }
            } else {
                appendLine("  General: Patient alert and oriented.")
                appendLine("  Per clinical encounter. See transcript for detailed findings.")
            }

            // Investigations ordered/resulted
            if (investigations.isNotEmpty()) {
                appendLine()
                appendLine("Investigations:")
                investigations.forEach { inv ->
                    if (inv.result != null) {
                        appendLine("  ${inv.test}: ${inv.result}")
                    } else {
                        appendLine("  ${inv.test}: ordered")
                    }
                }
            }
        }
    }

    private fun buildAssessment(diagnoses: List<Diagnosis>, alerts: List<CDSSAlert>, suggestedDiagnoses: List<Diagnosis> = emptyList()): String {
        return buildString {
            if (diagnoses.isNotEmpty()) {
                appendLine("Confirmed Diagnoses:")
                diagnoses.forEachIndexed { index, dx ->
                    val primary = if (dx.isPrimary) " [PRIMARY]" else ""
                    appendLine("${index + 1}. ${dx.description} (${dx.icd10Code})$primary")
                    appendLine("   Confidence: ${"%.0f".format(dx.confidence * 100)}%")
                }
            } else if (suggestedDiagnoses.isEmpty()) {
                appendLine("No formal diagnoses recorded.")
            }

            if (suggestedDiagnoses.isNotEmpty()) {
                if (diagnoses.isNotEmpty()) appendLine()
                appendLine("Suggested Diagnoses (pending clinician confirmation):")
                suggestedDiagnoses.forEachIndexed { index, dx ->
                    val primary = if (dx.isPrimary) " [PRIMARY]" else ""
                    appendLine("  ${index + 1}. ${dx.description} (${dx.icd10Code})$primary")
                    appendLine("     Confidence: ${"%.0f".format(dx.confidence * 100)}%")
                    appendLine("     Source: ${if (dx.source == "clinician") "clinician-selected" else "AI-suggested"}")
                }
            }

            if (alerts.isNotEmpty()) {
                appendLine()
                appendLine("Clinical Decision Support Alerts:")
                alerts.forEach { alert ->
                    val severity = when (alert.severity) {
                        AlertSeverity.CRITICAL -> "[CRITICAL]"
                        AlertSeverity.WARNING -> "[WARNING]"
                        AlertSeverity.INFO -> "[INFO]"
                    }
                    appendLine("  $severity: ${alert.message}")
                }
            }
        }
    }

    private fun buildPlan(
        medications: List<Medication>,
        encounter: EncounterEntity,
        diagnoses: List<Diagnosis>,
        referrals: List<ReferralEntity> = emptyList(),
        planItems: List<String> = emptyList()
    ): String {
        return buildString {
            // Plan items from clinical extraction (e.g., "start RHZE TB treatment", "continue ART")
            if (planItems.isNotEmpty()) {
                appendLine("Clinical Plan:")
                planItems.forEach { item ->
                    appendLine("  - $item")
                }
                appendLine()
            }

            // Medications
            if (medications.isNotEmpty()) {
                appendLine("Medications:")
                medications.forEachIndexed { index, med ->
                    val dosage = buildString {
                        append("  ${index + 1}. ${med.name}")
                        med.dose?.let { d ->
                            // Preserve decimal precision for fractional doses (e.g. 2.5mg)
                            val formatted = if (d % 1.0f == 0f) "${d.toInt()}" else "%.1f".format(d)
                            append(" $formatted")
                        }
                        med.unit?.let { append(it) }
                        med.frequency?.let { append(" $it") }
                        med.duration?.let { append(" for $it days") }
                        med.route?.let { append(" ($it)") }
                    }
                    appendLine(dosage)
                }
                appendLine()
            }

            // Follow-up
            encounter.followUpDays?.let { days ->
                appendLine("Follow-up:")
                appendLine("  Return in $days days.")
                encounter.followUpReason?.let {
                    appendLine("  Reason: $it")
                }
                appendLine()
            }

            // Referrals — use structured referral entities if available, else fall back to encounter fields
            if (referrals.isNotEmpty()) {
                appendLine("Referrals:")
                referrals.forEach { ref ->
                    appendLine("  → ${ref.toFacility}${ref.toDepartment?.let { " ($it)" } ?: ""}")
                    appendLine("    Urgency: ${ref.urgency}")
                    appendLine("    Reason: ${ref.reason}")
                    ref.clinicalNotes?.let { appendLine("    Notes: $it") }
                    appendLine("    Status: ${ref.status}")
                }
                appendLine()
            } else {
                encounter.normalizedReferralOrNull()?.let { referral ->
                    appendLine("Referral:")
                    appendLine("  Refer to: ${referral.type}${referral.specialty?.let { " (${it})" } ?: ""}")
                    appendLine("  Urgency: ${referral.urgency}")
                    referral.reason?.let { appendLine("  Reason: $it") }
                    appendLine()
                }
            }

            // Patient education
            appendLine("Patient Education:")
            diagnoses.forEach { dx ->
                appendLine("  - Discussed ${dx.description}, management, and warning signs.")
            }
            if (medications.isNotEmpty()) {
                appendLine("  - Medication instructions provided. Side effects discussed.")
            }
        }
    }

    private fun bpCategory(sys: Int, dia: Int): String = when {
        sys >= 180 || dia >= 120 -> " — HYPERTENSIVE CRISIS"
        sys >= 140 || dia >= 90 -> " — Stage 2 Hypertension"
        sys >= 130 || dia >= 80 -> " — Stage 1 Hypertension"
        sys >= 120 -> " — Elevated"
        else -> " — Normal"
    }

    private fun bmiCategory(bmi: Double): String = when {
        bmi < 18.5 -> " (Underweight)"
        bmi < 25.0 -> " (Normal)"
        bmi < 30.0 -> " (Overweight)"
        bmi < 35.0 -> " (Obese Class I)"
        bmi < 40.0 -> " (Obese Class II)"
        else -> " (Obese Class III)"
    }
}
